Temporarily disable CFLAGS += -Werror
due to visibilty warnings when compiling under MinGW on Windows like this:

cc1.exe: warnings being treated as errors
zlib/gzlib.c: In function 'gz_error':
zlib/gzlib.c:518:1: error: visibility attribute not supported in this configuration; ignored
make: *** [zlib/gzlib.o] Error 1